<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ModifyCollectionPoint.aspx.cs" Inherits="ADProject_Team10.DeptHead.ModifyCollectionPoint" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="OutlineElement Ltr SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: Arial; font-size: 9.28924px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <p class="Paragraph SCXP83996906" data-ccp-props="{&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559683&quot;:0,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;335559737&quot;:0,&quot;335562764&quot;:2,&quot;335562765&quot;:1,&quot;335562766&quot;:4,&quot;335562767&quot;:0,&quot;335562768&quot;:4,&quot;335562769&quot;:0}" lang="EN-SG" paraeid="{23254b95-b7ab-4b39-89a3-2e53291da203}{204}" paraid="0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; word-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;" xml:lang="EN-SG">
            <span class="TextRun SCXP83996906" lang="EN-SG" style="margin: 0px; padding: 1.33412px 0px 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-variant-ligatures: normal; color: rgb(0, 0, 0); font-weight: normal; font-style: normal; text-decoration: none; font-size: 11.6115px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif; font-variant-caps: normal; letter-spacing: 0px; font-kerning: normal; line-height: 14px; vertical-align: -1.33412px;" xml:lang="EN-SG"><span class="NormalTextRun SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; vertical-align: 1.33412px; line-height: 0px; position: relative;">Attention:</span></span><span class="EOP SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-size: 11.6115px; line-height: 0px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif;">​</span></p>
    </div>
    <ol class="NumberListStyle1 SCXP83996906" role="list" start="1" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; overflow: visible; cursor: text; list-style-type: decimal; color: rgb(0, 0, 0); font-family: Arial; font-size: 9.28924px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        <li class="OutlineElement Ltr SCXP83996906" data-aria-level="1" data-aria-posinset="1" data-buautonum="8" data-charcodes="65533,0,46" data-margin="540" role="listitem" style="margin: 0px 0px 0px 11.1969px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; vertical-align: baseline; font-family: Arial; font-size: 9.28924px;">
            <p class="Paragraph SCXP83996906" data-ccp-props="{&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559683&quot;:0,&quot;335559685&quot;:540,&quot;335559731&quot;:-540,&quot;335559737&quot;:0,&quot;335562764&quot;:2,&quot;335562765&quot;:1,&quot;335562766&quot;:4,&quot;335562767&quot;:0,&quot;335562768&quot;:4,&quot;335562769&quot;:0}" data-indent="-540" lang="EN-SG" paraeid="{23254b95-b7ab-4b39-89a3-2e53291da203}{207}" paraid="0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; word-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;" xml:lang="EN-SG">
                <span class="TextRun SCXP83996906" lang="EN-SG" style="margin: 0px; padding: 1.33412px 0px 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-variant-ligatures: normal; color: rgb(0, 0, 0); font-weight: normal; font-style: normal; text-decoration: none; font-size: 11.6115px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif; font-variant-caps: normal; letter-spacing: 0px; font-kerning: normal; line-height: 14px; vertical-align: -1.33412px;" xml:lang="EN-SG"><span class="NormalTextRun SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; vertical-align: 1.33412px; line-height: 0px; position: relative;">Collection of order on every Monday.</span></span><span class="EOP SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-size: 11.6115px; line-height: 0px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif;">​</span></p>
        </li>
        <li class="OutlineElement Ltr SCXP83996906" data-aria-level="1" data-aria-posinset="2" data-buautonum="8" data-charcodes="65533,0,46" data-margin="540" role="listitem" style="margin: 0px 0px 0px 11.1969px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; vertical-align: baseline; font-family: Arial; font-size: 9.28924px;">
            <p class="Paragraph SCXP83996906" data-ccp-props="{&quot;335551550&quot;:1,&quot;335551620&quot;:1,&quot;335559683&quot;:0,&quot;335559685&quot;:540,&quot;335559731&quot;:-540,&quot;335559737&quot;:0,&quot;335562764&quot;:2,&quot;335562765&quot;:1,&quot;335562766&quot;:4,&quot;335562767&quot;:0,&quot;335562768&quot;:4,&quot;335562769&quot;:0}" data-indent="-540" lang="EN-SG" paraeid="{23254b95-b7ab-4b39-89a3-2e53291da203}{210}" paraid="0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; word-wrap: break-word; font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;" xml:lang="EN-SG">
                <span class="TextRun SCXP83996906" lang="EN-SG" style="margin: 0px; padding: 1.33412px 0px 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-variant-ligatures: normal; color: rgb(0, 0, 0); font-weight: normal; font-style: normal; text-decoration: none; font-size: 11.6115px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif; font-variant-caps: normal; letter-spacing: 0px; font-kerning: normal; line-height: 14px; vertical-align: -1.33412px;" xml:lang="EN-SG"><span class="NormalTextRun SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; vertical-align: 1.33412px; line-height: 0px; position: relative;">Changes of collection point made after 8am of every Friday will not be reflected on delivery of next<span>&nbsp;</span></span><span class="NormalTextRun SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; vertical-align: 1.33412px; line-height: 0px; position: relative;">Monday. 
                It shall only be reflected on subsequent weeks after next week.</span></span><span class="EOP SCXP83996906" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; touch-action: pan-x pan-y; font-size: 11.6115px; line-height: 0px; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI_MSFontService&quot;, sans-serif;">​</span></p>
        </li>
    </ol>
    <p>
        Collection Point:&nbsp;
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:RadioButtonList ID="rblCollectionPoint" runat="server">
        </asp:RadioButtonList>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
    <p>
        Store Clerk In-Charged:&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblStoreClerkName" runat="server"></asp:Label>
    </p>
    <p>
        Time:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lbltime" runat="server"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
    <p>
        Contact Number&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblContactNumber" runat="server"></asp:Label>
    </p>
    <p>
        <br />
        <asp:Button ID="btnUpdate" runat="server" Text="Update" />
    </p>
    <br />
&nbsp;<p>
        &nbsp;</p>
</asp:Content>
